# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

require "capistrano/rails"
require "capistrano/rbenv"
require "capistrano/yarn"
require "capistrano/bundler"
require "capistrano/nginx"

require "capistrano/puma"
require "capistrano/puma/nginx"

install_plugin Capistrano::Nginx

install_plugin Capistrano::Puma
install_plugin Capistrano::Puma::Workers
install_plugin Capistrano::Puma::Nginx

require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
